apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    # Number of (idential) Pods that this Deployment will make
    replicas: 5
    selector:
        # This is how Deployment will later find/match Pods created by this Deployment
        matchLabels:
            component: web
    # Config for every single Pod created by this Deployment
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: client
                  image: cburkins/multi-worker
                  ports:
                      - containerPort: 9999
